name: universe
description: "UniVerse App - A Flutter application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.0.5
  flutter_screenutil: ^5.9.3
  retrofit: ^4.9.2
  dio: ^5.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.3.2
  go_router: ^16.3.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  logger: ^2.5.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  flutter_bloc: ^9.1.1
  retrofit_generator: ^10.2.1
  smooth_page_indicator: ^2.0.1
  flutter_native_splash: ^2.4.7
  awesome_dialog: ^3.3.0
  pinput: ^6.0.1
  animated_bottom_navigation_bar: ^1.4.0
  mobile_scanner: ^6.0.0
  url_launcher: ^6.3.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.12.0
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  flutter_launcher_icons: ^0.14.4
  skeletonizer: ^2.1.2
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/

# ================= SPLASH SCREEN =================
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/universe_logo.png

  android: true
  ios: true

  android_12:
    color: "#ffffff"
    image: assets/images/universe_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png    